### ISSUE TITLE
cp fails in v1.2.0

### ISSUE THREAD

**Issue by tehfink** [Emrion/uploaders#6]
Cool utility, thank you! 
On FreeBSD 13.3:

```
# ./loaders-update shoot-me
loaders-update v1.2.0

One or more efi partition(s) have been found.

Examining vtbd0p1...
mount -t msdosfs /dev/vtbd0p1 /mnt
About to execute: cp  /mnt/EFI/BOOT/BOOTX64.EFI
Are you sure (y/N)? y
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file ... target_directory
umount /mnt

One or more freebsd-boot partition(s) have been found.
The root file system is zfs.

Examining vtbd0...
About to execute: gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 2 vtbd0
Are you sure (y/N)? y
partcode written to vtbd0p2
bootcode written to vtbd0

-------------------------------
Your current boot method is UEFI.
Boot device: Misc Device PciRoot(0x0)/Pci(0x5,0x0)
Updatable EFI loader: 1
Updated BIOS loader: 1
One or more loaders may be updatable, but encountered 1 error(s).
```

Context:
```
# zpool list
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
zjail  46.5G  45.4G  1.09G        -         -    96%    97%  1.00x    ONLINE  -
zroot  38.2G  8.47G  29.8G        -         -    18%    22%  1.00x    ONLINE  -
```

```
# geom disk list
Geom name: vtbd0
Providers:
1. Name: vtbd0
   Mediasize: 50000000000 (47G)
   Sectorsize: 512
   Mode: r2w2e3
   descr: (null)
   ident: (null)
   rotationrate: unknown
   fwsectors: 63
   fwheads: 16

Geom name: vtbd1
Providers:
1. Name: vtbd1
   Mediasize: 50000000000 (47G)
   Sectorsize: 512
   Mode: r1w1e1
   descr: (null)
   ident: (null)
   rotationrate: unknown
   fwsectors: 63
   fwheads: 16
```

```
# gpart show
=>      40  97656176  vtbd0  GPT  (47G)
        40    409600      1  efi  (200M)
    409640      1024      2  freebsd-boot  (512K)
    410664       984         - free -  (492K)
    411648  16777216      3  freebsd-swap  (8.0G)
  17188864  80465920      4  freebsd-zfs  (38G)
  97654784      1432         - free -  (716K)
```

```
# freebsd-version -kru
13.3-RELEASE-p7
13.3-RELEASE-p7
13.3-RELEASE-p8
```

PS: looking forward to MBR support. I have a few old mac pros that still run FreeBSD great, and would love to safely upgrade their zfs on root for FBSD 14
